/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pemrogramanJaringan.pemrogramanJaringan.Stream;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author arema
 */
public class Notepad extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Notepad.class.getName());

    /**
     * Creates new form Notepad
     */
    public Notepad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NewFile = new javax.swing.JMenuItem();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Saveas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jMenu1.setText("File");

        NewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NewFile.setText("New File");
        NewFile.addActionListener(this::NewFileActionPerformed);
        jMenu1.add(NewFile);

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Open.setText("Open");
        Open.addActionListener(this::OpenActionPerformed);
        jMenu1.add(Open);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S,
                java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Save.setText("Save");
        Save.addActionListener(this::SaveActionPerformed);
        jMenu1.add(Save);

        Saveas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S,
                java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Saveas.setText("Save as");
        Saveas.addActionListener(this::SaveasActionPerformed);
        jMenu1.add(Saveas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private File file;

    private void NewFileActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NewFileActionPerformed
        file = null; // reset file yang sedang aktif
        TextArea.setText(""); // hapus isi text area
    }// GEN-LAST:event_NewFileActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveActionPerformed
        try {
            if (file != null) {

                OutputStream output = new FileOutputStream(file);
                output.write(TextArea.getText().getBytes());
                output.flush();
                output.close();
                JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");
            } else {
                SaveasActionPerformed(evt);
            }

        } catch (Exception e) {
            System.err.println("Terjadi kesalahan Pada Sistem!");
        }
    }// GEN-LAST:event_SaveActionPerformed

    private void SaveasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SaveasActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showSaveDialog(null);
            file = chooser.getSelectedFile();
            String fileName = file.getAbsolutePath().endsWith(".txt")
                    ? file.getAbsolutePath()
                    : file.getAbsolutePath() + ".txt";
            file = new File(fileName);
            OutputStream output = new FileOutputStream(file);
            output.write(TextArea.getText().getBytes());
            output.flush();
            output.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");

        } catch (Exception e) {
            System.err.println("Terjadi kesalahan Pada Sistem!");
        }
    }// GEN-LAST:event_SaveasActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_OpenActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            file = chooser.getSelectedFile();

            InputStream fileInput = new FileInputStream(file);
            StringBuilder text = new StringBuilder();

            int data;
            while ((data = fileInput.read()) != -1) {
                text.append((char) data);
            }

            fileInput.close();
            TextArea.setText(text.toString());

        } catch (IOException e) {
            System.err.println("Terjadi kesalahan Pada Sistem!");
        }
    }// GEN-LAST:event_OpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Notepad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem NewFile;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem Saveas;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
